name: release-8.4
on:
  push:
    tags:
    - 'v8.4.[0-9]+'
    - 'v8.4.[0-9]+-beta.[0-9]+'

jobs:
  docker-build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        build:
          - amd64
          - ppc64le
          - arm64
        include:
          - build: amd64
            arch: linux/amd64
          - build: ppc64le
            arch: linux/ppc64le
          - build: arm64
            arch: linux/arm64
    name: PHP 8.4 (${{ matrix.build }})
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: woodynew/phpswoole
          flavor: |
            latest=true
          tags: |
            type=semver,pattern={{major}}.{{minor}}-${{ matrix.build }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to DockerHub
        uses: docker/login-action@v3 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          provenance: false
          context: .
          platforms: ${{ matrix.arch }}
          file: php8.4-grpc/Dockerfile
          tags: ${{ steps.meta.outputs.tags }}

  docker-manifest:
    needs: docker-build
    runs-on: ubuntu-22.04
    steps:
      - name: Set envs
        run: |
          github_ref=${GITHUB_REF#refs/tags/}
          SEMVER=${github_ref##*v}
          echo "SEMVER=${SEMVER}" >> $GITHUB_ENV
          echo "SEMVER_MAJOR=${SEMVER%.*.*}" >> $GITHUB_ENV
          echo "SEMVER_MINOR=${SEMVER%.*}" >> $GITHUB_ENV
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Push semver minor alias
        run: |
          docker manifest create \
            woodynew/phpswoole:$SEMVER_MINOR \
              --amend woodynew/phpswoole:$SEMVER_MINOR-amd64 \
              --amend woodynew/phpswoole:$SEMVER_MINOR-ppc64le \
              --amend woodynew/phpswoole:$SEMVER_MINOR-arm64
          docker manifest push woodynew/phpswoole:$SEMVER_MINOR
      -
        name: Push latest (PHP 8.4 or newer)
        run: |
          docker manifest create \
            woodynew/phpswoole:latest \
              --amend woodynew/phpswoole:$SEMVER_MINOR-amd64 \
              --amend woodynew/phpswoole:$SEMVER_MINOR-ppc64le \
              --amend woodynew/phpswoole:$SEMVER_MINOR-arm64
          docker manifest push woodynew/phpswoole:latest
      -
        name: Pull all images
        run: |
          docker pull woodynew/phpswoole:$SEMVER_MINOR-amd64
          docker pull woodynew/phpswoole:$SEMVER_MINOR-ppc64le
          docker pull woodynew/phpswoole:$SEMVER_MINOR-arm64
      -
        name: Push semver alias
        run: |
          docker manifest create \
            woodynew/phpswoole:$SEMVER \
              --amend woodynew/phpswoole:$SEMVER_MINOR-amd64 \
              --amend woodynew/phpswoole:$SEMVER_MINOR-ppc64le \
              --amend woodynew/phpswoole:$SEMVER_MINOR-arm64
          docker manifest push woodynew/phpswoole:$SEMVER
      -
        name: Push semver major alias (PHP 8.4 or newer)
        run: |
          docker manifest create \
            woodynew/phpswoole:$SEMVER_MAJOR \
              --amend woodynew/phpswoole:$SEMVER_MINOR-amd64 \
              --amend woodynew/phpswoole:$SEMVER_MINOR-ppc64le \
              --amend woodynew/phpswoole:$SEMVER_MINOR-arm64
          docker manifest push woodynew/phpswoole:$SEMVER_MAJOR